// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdglJcaius-IkvEy9CxYWYsUooSPt1xYg',
    appId: '1:695114994326:web:075e77643ddc8fb4e428b7',
    messagingSenderId: '695114994326',
    projectId: 'calendar-schedule-kkong',
    authDomain: 'calendar-schedule-kkong.firebaseapp.com',
    storageBucket: 'calendar-schedule-kkong.appspot.com',
    measurementId: 'G-6NG3C2T928',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEq2L4yN94M9cozJKffoLopJEt9tMNunQ',
    appId: '1:695114994326:android:a2590d957f68c2f4e428b7',
    messagingSenderId: '695114994326',
    projectId: 'calendar-schedule-kkong',
    storageBucket: 'calendar-schedule-kkong.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPX-Z5Z739hMxWbHxBbx5-dmxbkoW1RHc',
    appId: '1:695114994326:ios:aaa4898737155641e428b7',
    messagingSenderId: '695114994326',
    projectId: 'calendar-schedule-kkong',
    storageBucket: 'calendar-schedule-kkong.appspot.com',
    iosClientId: '695114994326-h70jrk3dlod9j3rt3lhajnloe845eekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFactoryCalendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPX-Z5Z739hMxWbHxBbx5-dmxbkoW1RHc',
    appId: '1:695114994326:ios:aaa4898737155641e428b7',
    messagingSenderId: '695114994326',
    projectId: 'calendar-schedule-kkong',
    storageBucket: 'calendar-schedule-kkong.appspot.com',
    iosClientId: '695114994326-h70jrk3dlod9j3rt3lhajnloe845eekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFactoryCalendarScheduler',
  );
}
